#!/usr/bin/env python
"""
calculate_wer
"""
import argparse
import jiwer as jw
import json
from pathlib import Path

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('in_file', help='Input file')
  parser.add_argument('--output-dir','-o',
                      help='Output dir, if none is supplied then result is \
                      printed to stdout')
  args = parser.parse_args()

  in_path = Path(args.in_file)
  if save_output := args.output_dir is not None:
    out_path = Path(args.output_dir)

  if in_path.is_dir():
    pass

if __name__ == '__main__':
  main()
