#!/usr/bin/env python
"""
Generate a JSON encoding to represent data stored in a CSV file.

Expected column header: [speaker, fileID, transcript]
"""
import argparse
from utilities import TableToJSON

__author__ = "Adam Spencer"

def main():
  # Parse arguments
  parser = argparse.ArgumentParser(
      prog="generate_json",
      description="Generate a JSON encoding to represent data stored in a CSV file\n\nExpected header: [speaker, fileID, transcript]")

  parser.add_argument('filename', 
                      help="CSV file to encode in JSON format")
  parser.add_argument('--output', '-o', required=False,
                      default=None,
                      help="Path of output file, optional.")
  parser.add_argument('--index', '-i', required=False,
                      action='store_true', 
                      help="Use column 0 as index?")
  parser.add_argument('--verbose', '-v', required=False,
                      action='store_true',
                      help="Activate verbose output")
  args = parser.parse_args()

  table = TableToJSON(args.filename, args.index, args.verbose)  

  out = table.encode(args.output)

  if out:
    print(out)

if __name__ == '__main__':
  main()
